env:
  es6: true
  node: true
extends: 'eslint:recommended'
rules:
  comma-dangle:
    - error
    - always-multiline
  complexity:
    - error
    - 7
  indent:
    - error
    - 2
  key-spacing:
    - error
    - align: value
  linebreak-style:
    - error
    - unix
  max-len:
    - error
    - code: 80
  no-unused-vars:
    - error
    - args: none
  quotes:
    - error
    - double
  semi:
    - error
    - always
  valid-jsdoc:
    - error
    - matchDescription: .+
      prefer:
        arg: param
        argument: param
        return: returns
        virtual: abstract
      preferType:
        array: Array
        function: Function
        object: Object
        string: String
      requireParamDescription: true
      requireReturn: false
      requireReturnDescription: true
      requireReturnType: true
